/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unirio.acessorios;

/**
 *
 * @author Caroline
 */
public class Constants {
 
    public static final String ANO = "ANO";
    public static final String NATUREZA = "NATUREZA";
    public static final String ANODOTRABALHO = "ANO-DO-TRABALHO";
    public static final String ANODOARTIGO = "ANO-DO-ARTIGO";
    public static final String ARTIGOPUBLICADO = "ARTIGO-PUBLICADO";
    public static final String TRABALHOEMEVENTOS = "TRABALHO-EM-EVENTOS";
    public static final String DADOSBASICOSDOARTIGO = "DADOS-BASICOS-DO-ARTIGO";
    public static final String DETALHAMENTODOARTIGO = "DETALHAMENTO-DO-ARTIGO";
    public static final String DADOSBASICOSDOTRABALHO = "DADOS-BASICOS-DO-TRABALHO";
    public static final String DETALHAMENTODOTRABALHO = "DETALHAMENTO-DO-TRABALHO";
    public static final String TITULODOSANAISOUPROCEEDINGS = "TITULO-DOS-ANAIS-OU-PROCEEDINGS";
    public static final String TRABALHODECONCLUSAODECURSOGRADUACAO = "TRABALHO_DE_CONCLUSAO_DE_CURSO_GRADUACAO";
    public static final String ORIENTACAOEMANDAMENTODEGRADUACAO = "ORIENTACAO-EM-ANDAMENTO-DE-GRADUACAO";
    public static final String DADOSBASICOSDEOUTRASORIENTACOESCONCLUIDAS = "DADOS-BASICOS-DE-OUTRAS-ORIENTACOES-CONCLUIDAS";
    public static final String DADOSBASICOSDAORIENTACAOEMANDAMENTODEMESTRADO = "DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO";
    public static final String DADOSBASICOSDEORIENTACOESCONCLUIDASPARAMESTRADO = "DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-MESTRADO";
    public static final String DADOSBASICOSDEORIENTACOESCONCLUIDASPARADOUTORADO = "DADOS-BASICOS-DE-ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO";
    public static final String DADOSBASICOSDAPARTICIPACAOEMBANCADEMESTRADO = "DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-MESTRADO";
    public static final String DADOSBASICOSDAPARTICIPACAOEMBANCADEDOUTORADO = "DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-DOUTORADO";
    public static final String DADOSBASICOSDAPARTICIPACAOEMBANCADEGRADUACAO = "DADOS-BASICOS-DA-PARTICIPACAO-EM-BANCA-DE-GRADUACAO";
    public static final String DADOSBASICOSDAORIENTACAOEMANDAMENTODEDOUTORADO = "DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO";
    public static final String DADOSBASICOSDAORIENTACAOEMANDAMENTODEGRADUACAO = "DADOS-BASICOS-DA-ORIENTACAO-EM-ANDAMENTO-DE-GRADUACAO";
    public static final String ORIENTACOESCONCLUIDASPARAMESTRADO = "ORIENTACOES-CONCLUIDAS-PARA-MESTRADO";
    public static final String OUTRASORIENTACOESCONCLUIDAS = "OUTRAS-ORIENTACOES-CONCLUIDAS";
    public static final String ORIENTACOESCONCLUIDASPARADOUTORADO = "ORIENTACOES-CONCLUIDAS-PARA-DOUTORADO";
    public static final String ORIENTACAOEMANDAMENTODEMESTRADO = "ORIENTACAO-EM-ANDAMENTO-DE-MESTRADO";
    public static final String ORIENTACAOEMANDAMENTODEDOUTORADO = "ORIENTACAO-EM-ANDAMENTO-DE-DOUTORADO";
    public static final String PARTICIPACAOEMBANCADEMESTRADO = "PARTICIPACAO-EM-BANCA-DE-MESTRADO";
    public static final String PARTICIPACAOEMBANCADEDOUTORADO = "PARTICIPACAO-EM-BANCA-DE-DOUTORADO";
    public static final String PARTICIPACAOEMBANCADEGRADUACAO = "PARTICIPACAO-EM-BANCA-DE-GRADUACAO";
    public static final String TITULODOPERIODICOOUREVISTA = "TITULO-DO-PERIODICO-OU-REVISTA";
    
}
